export const projectsList = [
    {
      title: "Artists",
      description: "Our ambition is to offer all artists professional and personal management service. We offer online casting for new promising artists of all genres.",
      year: 2010,
      src: '/scene.jpg',
      alt: 'National Electronic Registry "The musical talents of Serbia',
      linkTo: '#contact'
    },
    {
      title: "WORLD OPEN Music Competition",
      description: "The oldest of all online competitions!",
      year: 2010,
      src: '/globe.jpg',
      alt: "WORLD OPEN Online Music Competition",
      linkTo: "https://musiccompetition.eu/"
    },
    {
      title: "EUROPE OPEN Music Competition",
      description: "New format of an online competition.",
      year: 2021,
      src: '/europe.jpg',
      alt: "EUROPE OPEN Online Music Competition",
      linkTo: "https://europecompetition.com/",
    },
    {
      title: "Love Story - Wedding Agency",
      description: "Our artists - screenwriters, decorators, florists, stylists, make-up artists, manicurists, photographers, videographers, music groups, presenters and other participants will be happy to help you create your perfect wedding!",
      year: 2016,
      src: '/wedding.jpg',
      alt: "Love Story - Wedding Agency",
      linkTo: "http://lovestory.rs/",
    },
    {
      title: "Russian School of Music Sergei Rachmaninoff",
      description: "Musical education in the historic center of Russian culture in Serbia - Russian Center for Science and Culture in Belgrade.",
      year: 2011,
      src: '/rachmaninoff.jpg',
      alt: "Russian School of Music S.V. Rachmaninov",
      linkTo: "https://www.facebook.com/groups/179402178788400",
    },
    {
      title: 'National Electronic Registry "The musical talents of Serbia"',
      description: 'The National Electronic Register "Musical Talents of Serbia" is an online database of talented young musicians from Serbia, Republic of Srpska and the diaspora.',
      year: 2011,
      src: '/conductor.jpg',
      alt: 'National Electronic Registry "The musical talents of Serbia',
      linkTo: "#contact",
    },
    {
      title: 'Russian Choir',
      description: 'A choir that promotes Russian culture and national music with its numerous performances.',
      year: 2014,
      src: '/russianchoir.jpg',
      alt: "Russian Choir",
      linkTo: "https://www.facebook.com/groups/1484138968514944",
    },
    {
      title: 'World Masterclass',
      description: 'Masterclass with outstanding musicians and teachers. Masterclasses are open to pupils, students and teachers.',
      year: 2012,
      src: '/violin.jpg',
      alt: "World Master Class",
      linkTo: "#contact",
    },
  ];